# Generated by Django 4.2.4 on 2024-01-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_link', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150, verbose_name='Называние канала')),
                ('pictures', models.ImageField(upload_to='', verbose_name='Лого')),
                ('subscribers', models.IntegerField()),
                ('views', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Канал',
                'ordering': ['-subscribers'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=140),
        ),
    ]
