# Generated by Django 4.2.4 on 2024-01-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_chanel_alter_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_link', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='backend.profile')),
            ],
        ),
    ]
