# Generated by Django 4.2.4 on 2024-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_category_chanels_like_add_chanel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_userbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=100)),
                ('session', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Is this userbot active?')),
            ],
        ),
    ]
