# Generated by Django 4.2.4 on 2024-01-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_chanel_add_chanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qiwi',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
