# Generated by Django 4.2.4 on 2024-01-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_profile_qiwi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chanel',
            name='category',
        ),
    ]
