# Generated by Django 4.2.4 on 2024-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_add_chanel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
