# Generated by Django 4.2.4 on 2024-03-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_chanel_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chanel',
            old_name='update_date',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='chanel',
            name='daily_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='weekly_monthy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='weekly_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='add_chanel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.add_chanel'),
        ),
    ]
