# Generated by Django 4.2.4 on 2024-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_update_date_chanel_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='mentioned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chanel',
            name='posts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
