# Generated by Django 4.2.4 on 2024-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_chanel_mentioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chanel',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
