# Generated by Django 4.2.4 on 2024-04-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_chanel_description_alter_chanel_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chanel',
            name='description',
        ),
    ]
