# Generated by Django 4.2.4 on 2024-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_chanel_daily_views_chanel_yesterday_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='posts_today',
            field=models.IntegerField(default=0),
        ),
    ]
