# Generated by Django 4.2.4 on 2024-04-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_chanel_posts_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='posts_today',
        ),
    ]
