# Generated by Django 4.2.4 on 2024-04-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_chanel_posts_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='mentioned',
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('view', models.IntegerField()),
                ('media', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mention', models.BooleanField(default=False)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='backend.chanel')),
            ],
        ),
    ]
