# Generated by Django 4.2.4 on 2024-04-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_chanel_mentioned_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPerday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subperday', models.IntegerField()),
                ('viewsperday', models.IntegerField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subperday', to='backend.chanel')),
            ],
            options={
                'unique_together': {('chanel', 'created_at')},
            },
        ),
    ]
