# Generated by Django 4.2.4 on 2024-04-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_subperday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subperhour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subperhour', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subperhour', to='backend.chanel')),
            ],
            options={
                'unique_together': {('chanel', 'created_at')},
            },
        ),
    ]
