# Generated by Django 4.2.4 on 2024-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_like_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='node',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
