# Generated by Django 4.2.4 on 2024-04-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_like_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chanel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_chanel', to='backend.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='backend.profile'),
            preserve_default=False,
        ),
    ]
