# Generated by Django 4.2.4 on 2024-04-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_add_chanel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('id_channel', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='backend.chanel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='backend.posts')),
            ],
        ),
    ]
