# Generated by Django 4.2.4 on 2024-04-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='posts',
        ),
    ]
