# Generated by Django 4.2.4 on 2024-04-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_chanel_chanel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='id_channel_forward_from',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
