# Generated by Django 4.2.4 on 2024-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_posts_id_channel_forward_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id_channel_forward_from',
            field=models.IntegerField(null=True),
        ),
    ]
