# Generated by Django 4.2.4 on 2024-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_posts_id_channel_forward_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.CharField(max_length=250),
        ),
    ]
