# Generated by Django 4.2.4 on 2024-05-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_posts_date_alter_posts_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentions',
            name='id_channel',
        ),
        migrations.RemoveField(
            model_name='mentions',
            name='id_post',
        ),
    ]
