# Generated by Django 4.2.4 on 2024-05-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_mentions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_post', to='backend.posts'),
        ),
    ]
