# Generated by Django 4.2.4 on 2024-05-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_mentions_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subperhour',
            options={'ordering': ['-created_at']},
        ),
    ]
