# Generated by Django 4.2.4 on 2024-05-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_subperhour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentions',
            options={'ordering': ['-mentioned_channel']},
        ),
    ]
