# Generated by Django 4.2.4 on 2024-05-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date']},
        ),
    ]
