# Generated by Django 4.1.2 on 2024-06-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_add_chanel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chanel',
            name='chanel_id',
        ),
    ]
