# Generated by Django 4.1.2 on 2024-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_chanel_img_remove_profile_qiwi_profile_telegram_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_bio',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
