# Generated by Django 4.2.4 on 2024-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_remove_profile_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
