# Generated by Django 4.2.4 on 2024-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_remove_profile_currency_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_bio',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_first_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_last_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
