# Generated by Django 4.2.4 on 2024-09-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_profile_notify_bio_profile_notify_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notify_first_name',
            new_name='notify_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notify_last_name',
        ),
    ]
