# Generated by Django 4.2.4 on 2024-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_rename_notify_first_name_profile_notify_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='forwards_count',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
