# Generated by Django 4.2.4 on 2024-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_posts_forwards_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
