# Generated by Django 4.2.4 on 2024-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='check_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='notify',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
