# Generated by Django 4.2.4 on 2024-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_notify_check_date_notify_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='check_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
