# Generated by Django 4.2.4 on 2024-09-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_alter_notify_check_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_chanel', to='backend.chanel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to='backend.profile')),
            ],
        ),
    ]
