# Generated by Django 4.2.4 on 2024-09-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_dempo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dempo',
            new_name='Demo',
        ),
    ]
