# Generated by Django 4.2.4 on 2024-10-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='profile',
        ),
    ]
