# Generated by Django 4.2.4 on 2024-10-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_remove_commission_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='backend.ref'),
        ),
    ]
