# Generated by Django 4.2.4 on 2024-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_alter_commission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='Type_notify',
            field=models.CharField(choices=[('chanel', 'Упоминания канала '), ('word', ' Упоминание слова и фразы')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
