# Generated by Django 4.2.4 on 2024-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_notify_type_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chanel',
            name='chanel_link',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
