# Generated by Django 4.2.4 on 2024-10-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_remove_payment_paymentgatway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentgatway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.paymentgateway'),
            preserve_default=False,
        ),
    ]
