# Generated by Django 4.2.4 on 2024-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_payment_paymentgatway'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
