# Generated by Django 4.2.4 on 2024-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_subscribe_status_type_sub_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
