# Generated by Django 4.2.4 on 2024-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_profile_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentgatway',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
