# Generated by Django 4.2.4 on 2024-12-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_alter_payment_paymentgatway_delete_paymentgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chanel',
            name='username',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_chanel', to='backend.profile'),
        ),
    ]
