# Generated by Django 4.2.4 on 2024-12-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_alter_chanel_add_chanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='add_chanel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.profile'),
        ),
    ]
