# Generated by Django 4.2.4 on 2025-01-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_alter_chanel_add_chanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_sub',
            name='discout',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='discout_minus',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='one_dollar',
            field=models.BooleanField(default=False),
        ),
    ]
