# Generated by Django 4.2.4 on 2025-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_type_sub_discout_type_sub_discout_minus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_sub',
            name='discout_en',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='discout_minus_en',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type_sub',
            name='price_rubl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
