# Generated by Django 4.2.4 on 2025-01-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_type_sub_discout_en_type_sub_discout_minus_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_sub',
            name='price_rubl',
        ),
    ]
