# Generated by Django 4.2.4 on 2025-01-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_remove_type_sub_price_rubl'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='amount_rubl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
