# Generated by Django 4.2.4 on 2025-01-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_commission_amount_rubl'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_rubl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
