# Generated by Django 4.2.4 on 2025-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_payment_amount_rubl'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
