# Generated by Django 4.2.4 on 2025-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_posts_photo_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/'),
        ),
    ]
