# Generated by Django 4.2.4 on 2025-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_alter_posts_photo_alter_posts_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
