# Generated by Django 4.2.4 on 2025-11-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_alter_posts_photo_alter_posts_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_chanel',
            name='category',
        ),
        migrations.AddField(
            model_name='add_chanel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category_chanels'),
        ),
    ]
