# Generated by Django 4.2.4 on 2025-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_remove_add_chanel_category_add_chanel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chanel',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='add_chanel',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
