# Generated by Django 4.2.4 on 2025-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_add_chanel_country_add_chanel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_chanels',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/'),
        ),
    ]
