# Generated by Django 4.2.4 on 2025-11-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_category_chanels_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_chanels',
            name='icon',
            field=models.FileField(null=True, upload_to='icons/'),
        ),
    ]
