# Generated by Django 4.2.4 on 2025-11-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_alter_category_chanels_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='chanels',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.add_chanel'),
        ),
    ]
