# Generated by Django 4.2.4 on 2026-03-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_chanel_chanels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AddField(
            model_name='posts',
            name='media_file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
